### PR TITLE
feat: csv reporter

### PR DESCRIPTION
**Pull request by sergiojoker11**
Includes:
 - task to output report in CSV format
 - code implementing mentioned feature.
 - 1 test. Happy to implement more if you think it is necessary

### CODE REVIEW

**Comment by rtimush** [comment]
Thank you for the contribution!

**Comment by sergiojoker11** [comment]
You're welcome!
Any idea when it is going to be released?

**Comment by rtimush** [comment]
I just published 0.6.4, it should be available soon.

**Comment by sergiojoker11** [comment]
> I just published 0.6.4, it should be available soon.

Should it not be 0.7.0 since this is a new feature?

**Comment by sergiojoker11** [comment]
Forgot to update readme file: https://github.com/sergiojoker11/sbt-updates/pull/1

**Pull request merged**
