### PR TITLE
Detect plugin updates on maven central

### LINKED ISSUE #108: Failed to find updates for sbt plugins published to maven central
file:project/plugins.sbt
```
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
```

sbt-updates added either as a global plugin or project plugin fails to find an update 2.0.1 to this plugin.

This might be due to some sbt plugins published maven style do not generate maven-metadata.xml

Enabling debug mode you can see that a call is made to https://repo1.maven.org/maven2/org/scalameta/sbt-scalafmt_2.12_1.0/maven-metadata.xml which returns 404, but if you remove maven-metadata.xml the page exists

### PR DESCRIPTION
**Pull request by rtimush**
If there is no `maven-metadata.xml` found (which for example happens when an sbt plugin is published to a Maven repository) try ivy-style version extraction. Also adjusts HTML extraction regex to handle more cases.

Fixes #108.

### CODE REVIEW

**Comment by fthomas** [comment]
It will be interesting to use this in scala-steward. I guess it will update quite a few plugins.

**Comment by rtimush** [comment]
@fthomas I will try to make a release of `sbt-updates` soon. I guess that's what you need to use it in scala-steward, right?

**Comment by fthomas** [comment]
Yes, scala-steward currently uses only released versions of sbt-updates. But I don't want to pressure you into cutting a new release. My comment was just meant as observation that this feature will probably result in quite a few PRs. :-)

**Comment by fthomas** [comment]
FYI: @scala-steward created 550+ PRs because of this change. :-) So thanks again for working on this!

**Pull request merged**
